bert_config: '/home/mnt/cv/acformer/configs/config_bert.json'

image_size: 224
image_res: 224
num_frames: 4

vision_width: 75 # Visual Features 75 for UR_FUNNY
audio_width: 81  # Acoustic Features  81 for UR_FUNNY
text_width: 768
embed_dim: 768

mlp_ratio: 4.0
dropout: 0.1
neck_size: 6
positional_embedding: learnable #  {'sine', 'learnable', 'none'}
freq_bins: 768
time_frames: 1024

num_layers: 5
start_fusion_layer: 3
fusion_head: 6
fusion_strategy: separate # residual
# fusion_strategy: separate # residual

batch_size: 8
temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4
warm_up: True

optimizer: {opt: adamW, lr: 0.00005, weight_decay: 0.02}
schedular: {sched: cosine, lr: 0.00001, epochs: 30, min_lr: 0.00001, decay_rate: 1, warmup_lr: 0.00005, warmup_epochs: 5, cooldown_epochs: 0}

# dataset configs
data_dir: /home/mnt/cv/acformer/data/ur_funny
dataset_dir: /home/mnt/cv/acformer/data/ur_funny
sdk_dir: /home/mnt/cv/acformer/mmsdk/
word_emb_path: /home/mnt/cv/acformer/data/glove.840B.300d.txt

# model
num_classes: 2
loss_type: bce
distill: True

